config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/secret'
  root "static_pages#index"
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, optional: true
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_devise_parameters, if: :devise_controller?

    def configure_devise_parameters
      devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
      devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
    end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  def index
  end

  def secre
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestEBook7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

  </head>

  <body style="background-color:rgba(160,64,0,0.5);">

<ul class="nav justify-content-center"  style="background-color:rgba(160,64,0);">
  <li class="nav-item">
    <a><%= link_to 'connexion',  user_session_path, :class => "nav-link", style: "color:white"  %></a>
  </li>
  <li class="nav-item">
    <a><%= link_to 'nous rejoindre', new_user_registration_path, :class => "nav-link", style: "color:white"  %></a>
  </li>
  <li class="nav-item">
    <a><%= link_to 'abonement', user_session_path, :class => "nav-link", style: "color:white"  %></a>
  </li>
  <li class="nav-item">
   <a><%= link_to 'se deconnecter',  destroy_user_session_path, :class => "nav-link", style: "color:white"  %></a>
  </li>
</ul>
    <%= yield %>
    
  </body>
</html>

app/views/static_pages/index.html.erb
<br><center><h1> <p style="color:brown";><i>Notre boutique en ligne</i></p></h1></center>
<br>
<br>
<div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card h-100">
      <img src="https://cdn.pixabay.com/photo/2016/03/18/15/02/ufo-1265186_1280.jpg" class="card-img-top" alt="Image" height="300" width="300">
      <div class="card-body">
        <h5 class="card-title"><h1><i>science fiction</i></h1></h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
      <img src="https://static.actu.fr/uploads/2014/12/Jean-jacques-Banide-livres-et-arme-%C2%A9-quimper-communaute3575.jpg" class="card-img-top" alt="Image" height="300" width="300">
      <div class="card-body">
        <h5 class="card-title"><h1><i>policier</i></h1></h5>
        <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
      <img src="https://cdn.pixabay.com/photo/2018/01/21/01/46/architecture-3095716_1280.jpg" class="card-img-top" alt="Image" height="300" width="300">
      <div class="card-body">
        <h5 class="card-title"><h1><i>conte</i></h1></h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div>
    </div>
  </div>
</div>
<br>

<div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card h-100">
      <img src="https://cdn.pixabay.com/photo/2015/11/19/21/11/atlas-1052011_1280.jpg" class="card-img-top" alt="Image" height="300" width="300">
      <div class="card-body">
        <h5 class="card-title"><h1><i>éducation</i></h1></h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
      <img src="https://cdn.pixabay.com/photo/2015/05/07/15/48/bustos-756620_1280.jpg" class="card-img-top" alt="Image" height="300" width="300">
      <div class="card-body">
        <h5 class="card-title"><h1><i>philosophy</i></h1></h5>
        <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
      <img src="https://cdn.pixabay.com/photo/2017/07/22/11/46/adventure-2528477_1280.jpg" class="card-img-top" alt="Image" height="300" width="300">
      <div class="card-body">
        <h5 class="card-title"><h1><i>aventure</i></h1></h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div>
    </div>
  </div>
</div>

<br>
<center>
      <% if user_signed_in? %>
        <li>
          <i><%= link_to "Se déconnecter", destroy_user_session_path, style: "color:brown", method: :delete %></i>
        </li>

        <li>
          Voici ton email : <%= current_user.email %>
        </li>

        <li>
         <i><%= link_to  "Nos abonments", static_pages_secret_path, style: "color:brown"%></i>
        </li>

        <li>
          <i><%= link_to "Edit email / password", edit_user_registration_path, style: "color:brown" %></i>
        </li>

      <% else %>
        <li>    
         <i> <%= link_to "connexion", new_user_session_path, style: "color:brown" %></i>
        </li>

        <li>
          <i><%= link_to "S'inscrire", new_user_registration_path, style: "color:brown"%></i>
        </li>

      <% end %>
    </ul></center>
    

app/views/static_pages/secret.html.erb
<h1>nos abonments</h1>
<p>Find me in app/views/static_pages/secre.html.erb</p>